#!/usr/bin/env python
from FEC_grabber import stream_file
import db_docker
import requests
import os


def main():
    # start docker instance
    neo4j_docker_db = db_docker.Neo4jDockerDB()

    # create a node to store which files have been imported
    id = None
    try:
        id = neo4j_docker_db.get_node_id_by_name("Imported", "Imported")
    except db_docker.Neo4jAPIException:
        id = neo4j_docker_db.create_node("Imported", f"Name:'Imported'")

    # download the FEC data files to local dir: ./FEC_Election_Data
    file = stream_file("./FEC_Election_Data",
                       "https://www.fec.gov/files/bulk-downloads/2022/"
                       "candidate_summary_2022.csv")
    

if __name__ == '__main__':
    main()
